// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebAppCourierTrack;

#nullable disable

namespace WebAppCourierTrack.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20260610050358_TablasIndependientes")]
    partial class TablasIndependientes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebAppCourierTrack.Entidades.Estado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("Estados");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Pendiente"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Asignado"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "En camino"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Entregado"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Cancelado"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Confirmado"
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "En espera"
                        },
                        new
                        {
                            Id = 8,
                            Nombre = "Retrasado"
                        },
                        new
                        {
                            Id = 9,
                            Nombre = "Devuelto"
                        },
                        new
                        {
                            Id = 10,
                            Nombre = "Completado"
                        });
                });

            modelBuilder.Entity("WebAppCourierTrack.Entidades.EstadoPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("EstadoPagos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Pagado"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Pendiente"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Rechazado"
                        });
                });

            modelBuilder.Entity("WebAppCourierTrack.Entidades.ExtensionCI", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("ExtensionCI");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "LP"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "CB"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "SC"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "OR"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "PT"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "CH"
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "TJ"
                        },
                        new
                        {
                            Id = 8,
                            Nombre = "BN"
                        },
                        new
                        {
                            Id = 9,
                            Nombre = "PD"
                        });
                });

            modelBuilder.Entity("WebAppCourierTrack.Entidades.Genero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Generos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "FEMENINO"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "MASCULINO"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "OTRO"
                        });
                });

            modelBuilder.Entity("WebAppCourierTrack.Entidades.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "ADMINISTRADOR"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "CONDUCTOR"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "CLIENTE"
                        });
                });

            modelBuilder.Entity("WebAppCourierTrack.Entidades.TipoCliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("TipoClientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "JURIDICO"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "NATURAL"
                        });
                });

            modelBuilder.Entity("WebAppCourierTrack.Entidades.TipoDocumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("TipoDocumentos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "CEDULA DE IDENTIDAD"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "NIT"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
